default:
    type:     rest
    resource: CoreBundle\Controller\DefaultController

tournament:
    type:     rest
    resource: CoreBundle\Controller\TournamentController
battle:
    type:     rest
    resource: CoreBundle\Controller\BattleController
