services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%] 
    user.images_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%accounts_images_directory%']
    user.banners_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%accounts_banners_directory%']