services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%] 
    user.images_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%accounts_images_directory%']
    user.banners_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%accounts_banners_directory%']
    tournament.battle_listener:
        class: CoreBundle\EventListener\BattleListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
           - { name: kernel.event_subscriber }
    tournament.nextmatch_listener:
        class: CoreBundle\EventListener\NextMatchListener
        arguments: ['@doctrine.orm.entity_manager', '@user.notification']
        tags:
           - { name: kernel.event_subscriber }
    user.manage_experience:
        class: CoreBundle\Service\SetExperience
        arguments: ['@doctrine.orm.entity_manager']
    acme_hello.topic_sample_service:
        class: CoreBundle\Topic\CoreTopic
        tags:
            - { name: gos_web_socket.topic }
    app.exception_listener:
        class: CoreBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 15 }
    user.notification:
        class: CoreBundle\Service\SetNotification
        arguments: ['@doctrine.orm.entity_manager']
