services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%] 
    user.images_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%accounts_images_directory%']
    user.banners_uploader:
        class: CoreBundle\Service\FileUploader
        arguments: ['%accounts_banners_directory%']
    tournament.battle_listener:
        class: CoreBundle\EventListener\BattleListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
           - { name: kernel.event_subscriber }
    tournament.nextmatch_listener:
        class: CoreBundle\EventListener\NextMatchListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
           - { name: kernel.event_subscriber }
    user.manage_experience:
        class: CoreBundle\Service\SetExperience
        arguments: ['@doctrine.orm.entity_manager']
    corebundle.repository.experience:
        class: CoreBundle\Entity\LevelRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['CoreBundle:Level']