<?php

namespace CoreBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLastNotif($account)
	{
		$query = $this->createQueryBuilder('n')
			->select('n')
			->setParameter('account', $account)
			->where('n.account = :account')
			->AndWhere('n.isSeen = false')
			->setMaxResults(1)
			->orderBy('n.createdAt', 'DESC')
			->getQuery();
		return $query->getResult();
	}
}
