<?php

namespace CoreBundle\Repository;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByState($account_id)
	{
		$query = $this->createQueryBuilder('t')
			->select('COUNT(t)')
			->setParameter('account_id', $account_id)
			->where('t.account = :account_id')
			->AndWhere('t.state != 4')
			->getQuery();
		return $query->getSingleScalarResult();
	}
}
